In [2]:
import numpy as np
from sklearn import datasets

In [3]:
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [13]:
y_test[:52]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1])

In [14]:
X_train.shape

(1347, 64)

In [15]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

/Users/shenshaohong/.virtualenvs/LeeML/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9755555555555555

In [17]:
log_reg.decision_function(X_test)[:52]

array([-22.05699728, -33.02941489, -16.21335088, -80.37916297,
       -48.25125309, -24.54006521, -44.39168581, -25.0429477 ,
        -0.97828839, -19.71745384, -66.25139278, -51.09603001,
       -31.49349159, -46.05334697, -38.67877272, -29.80472044,
       -37.58850411, -82.57570297, -37.81904378, -11.01165598,
        -9.17440282, -85.13004858, -16.71616451, -46.2372651 ,
        -5.32994343, -47.91762424, -11.66730613, -39.19606675,
       -25.25294596, -14.36647263, -16.99784322, -28.91906343,
       -34.33942078, -29.47608376,  -7.85813331,  -3.82093432,
       -24.08165466, -22.16362793, -33.61221199, -23.14024239,
       -26.91805368, -62.38938376, -38.85691793, -66.7726097 ,
       -20.14483425, -17.47887025, -18.06800222, -22.22226081,
       -29.62304646, -19.73171496,   1.49551643,   8.32080732])

In [9]:
y_log_predict = log_reg.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_log_predict)

array([[403,   2],
       [  9,  36]])

In [11]:
from sklearn.metrics import precision_score

precision_score(y_test, y_log_predict)

0.9473684210526315

In [12]:
from sklearn.metrics import recall_score

recall_score(y_test, y_log_predict)

0.8